### ISSUE TITLE
Missing screens umbrella issue

### ISSUE THREAD

**Issue by hftf** [hftf/coords#41]
#### Battle
- [x] Give a nickname to this Pokémon?
- [x] Forget or keep a move?
- [x] Stop learning new move?
- [x] Which move to forget?

---

Leave a comment here to report a screen that is completely missing.
(To report an existing screen that is only missing an image, see #42 instead.)
